### ISSUE TITLE
iRevNet.py's test code doesn't work

### ISSUE THREAD

**Issue by SelimChraibi** [jhjacobsen/pytorch-i-revnet#16]
Hi, 

I tried running the script you provide in `models.iRevNet.py`:

```python
model = iRevNet(nBlocks=[6, 16, 72, 6], nStrides=[2, 2, 2, 2],
                    nChannels=None, nClasses=1000, init_ds=2,
                    dropout_rate=0., affineBN=True, in_shape=[3, 224, 224],
                    mult=4)
y = model(Variable(torch.randn(1, 3, 224, 224)))
print(y.size())
```

However, this seems to raise an error:

```bash
 == Building iRevNet 301 == 
Traceback (most recent call last):
  File "iRevNet.py", line 158, in <module>
    y = model(Variable(torch.randn(1, 3, 224, 224)))
  File "/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "iRevNet.py", line 132, in forward
    out = block.forward(out)
  File "iRevNet.py", line 61, in forward
    y1 = Fx2 + x1
RuntimeError: The size of tensor a (6) must match the size of tensor b (24) at non-singleton dimension 1
``` 

Am I doing something wrong?

Thanks!

**Comment by ZhipengCai** [comment]
Hi Selim,

Has this problem be solved? I encountered the same problem.

**Comment by SmileRussell** [comment]
Hi Selim,

Has this problem be solved? I encountered the same problem

**Comment by zxiaomzxm** [comment]
Change `nChannels` from `None` to `[24, 96, 384, 1536]`,
Ref: [https://github.com/jhjacobsen/pytorch-i-revnet/issues/5](url)

**Comment by jhjacobsen** [comment]
@zxiaomzxm thanks! fixed it.
